server:
  port: ${PORT:8081}

stripe:
  api:
    key: ${STRIPE_SECRET_KEY:sk_test_placeholder}

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://db-postgresql-sfo2-79244-do-user-22261196-0.m.db.ondigitalocean.com:25060/defaultdb?sslmode=require}
    driverClassName: org.postgresql.Driver
    username: ${SPRING_DATASOURCE_USERNAME:doadmin}
    password: ${SPRING_DATASOURCE_PASSWORD:}
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true

logging:
  level:
    org.hibernate.SQL: DEBUG
    com.ecommerce: DEBUG

smartlogix:
  webhook:
    url: ${SMARTLOGIX_WEBHOOK_URL}
    secret: ${SMARTLOGIX_WEBHOOK_SECRET}

